#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source ../settings/scripts/ynh_mongo_db__2
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

#REMOVEME? ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
#REMOVEME? ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
#REMOVEME? ynh_print_info --message="Loading installation settings..."

#REMOVEME? app=$YNH_APP_INSTANCE_NAME

#REMOVEME? #REMOVEME? install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
#REMOVEME? domain=$(ynh_app_setting_get --app=$app --key=domain)
#REMOVEME? html_path=$(ynh_app_setting_get --app=$app --key=html_path)
#REMOVEME? document_path=$(ynh_app_setting_get --app=$app --key=document_path)
#REMOVEME? public_key=$(ynh_app_setting_get --app=$app --key=public_key)

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

### N.B. : the following 'ynh_backup' calls are only a *declaration* of what needs
### to be backuped and not an actual copy of any file. The actual backup that
### creates and fill the archive with the files happens in the core after this
### script is called. Hence ynh_backups calls takes basically 0 seconds to run.

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup --src_path="$install_dir"

#=================================================
# BACKUP THE HTML AND DOCUMENT DIR
#=================================================

ynh_backup --src_path="$html_path" --is_big

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
if [ -n "$public_key" ]
then
  ynh_backup --src_path="/etc/sudoers.d/$app-sudoers"
fi


# BACKUP LOGROTATE
#=================================================

ynh_backup --src_path="/etc/logrotate.d/$app"

#=================================================
# BACKUP SYSTEMD services
#=================================================

for service_name in "${SERVICES_LIST[@]}"
do
  ynh_backup --src_path="/etc/systemd/system/${app}-${service_name}.service"
done

#=================================================
# BACKUP VARIOUS FILES
#=================================================

# ynh_backup --src_path="/etc/cron.d/$app"

#=================================================
# BACKUP THE MONGO DATABASES
#=================================================
ynh_print_info --message="Backing up the Mongo databases..."

for db_name in "${MONGO_DB_LIST[@]}"
do
  ynh_mongo_dump_db --database=$db_name > ./dump-${db_name}.bson
done

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
