#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd services..."

for service_name in "${SERVICES_LIST[@]}"; do
    ynh_systemctl --service="${app}-${service_name}" --action="stop"

done

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# Update document url in .env
#=================================================
ynh_script_progression "Updating .env configuration..."

new_document_url=$(append_uri "https://${new_domain}${new_path}" "docs")
ynh_app_setting_set --key=document_url --value="$new_document_url"

ynh_backup_if_checksum_is_different "$install_dir/.env"
ynh_replace --match="$document_url" --replace="$new_document_url" --file="$install_dir/.env"
ynh_store_file_checksum "$install_dir/.env"

# Update the repository pages
ynh_config_add --template="repository-next.json" --destination="$data_dir/repository-next.json"
ynh_config_add --template="repository-stable.json" --destination="$data_dir/repository-stable.json"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd services..."

for service_name in "${SERVICES_LIST[@]}"; do
    ynh_systemctl --service="${app}-${service_name}" --action="start"

done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
