#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:$app" "$install_dir"
#=================================================
# Configure document storage
#=================================================
ynh_script_progression "Configuring document storage..."

document_dir=$data_dir/docs
ynh_app_setting_set --key=document_dir --value="$document_dir"

document_url=$(append_uri "https://${domain}${path}" "docs")
ynh_app_setting_set --key=document_url --value="$document_url"

# Add the status pageindex
ynh_config_add --template="index.html" --destination="$data_dir/index.html"

# Add the repository pages
ynh_config_add --template="repository-next.json" --destination="$data_dir/repository-next.json"
ynh_config_add --template="repository-stable.json" --destination="$data_dir/repository-stable.json"

chmod -R o-rwx "$data_dir"
chown -R $app:www-data "$data_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

# The .env needs db_user and db_password
new_db_pwd=$(ynh_string_random) # Generate a random password
db_pwd="${db_pwd:-$new_db_pwd}"

db_user=$(ynh_sanitize_dbid --db_name="${app}")
ynh_app_setting_set --key=db_user --value="$db_user"

ynh_config_add --template=".env" --destination="$install_dir/.env"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/.env"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/.env"

#=================================================
# ADD SSH ACCESS
#=================================================

if [ -n "$public_key" ]; then
    ynh_script_progression "Enabling ssh access for dev..."
    # enable ssh access to the files for updates
    # todo: Secure it more with https://github.com/YunoHost-Apps/ssh_chroot_dir_ynh
    mkdir --parents "$install_dir/.ssh"
    ynh_config_add --template="authorized_keys" --destination="$install_dir/.ssh/authorized_keys"

    chown -R "$app:$app" "$install_dir/.ssh"
    chmod 700 "$install_dir/.ssh"
    chmod 600 "$install_dir/.ssh/authorized_keys"

    _install_restart_script_and_sudoers
fi

#=================================================
# INSTALL MONGO
#=================================================
ynh_script_progression "Installing MongoDB..."

# Install the required version of Mongo
ynh_install_mongo

#=================================================
# CREATE A MONGO DATABASE
#=================================================
ynh_script_progression "Creating the Mongo databases..."

for db_name in "${MONGO_DB_LIST[@]}"; do
    ynh_mongo_setup_db --db_user="$db_user" --db_pwd="$db_pwd" --db_name="dontCode$tenant${db_name}"
done

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

for i in "${!SERVICES_LIST[@]}"; do
    service_name="${SERVICES_LIST[i]}"
    port="${PORT_LIST[i]}"
    ynh_config_add_systemd --service="${app}-${service_name}"
    yunohost service add "${app}-${service_name}" --description="Dont-code platform ${service_name} service" --log="/var/log/${app}/${service_name}-${app}.log"
done

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd services..."

# Start a systemd service
for service_name in "${SERVICES_LIST[@]}"; do
    ynh_systemctl --service="${app}-${service_name}" --action="start"

done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
