#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
for service_name in "${SERVICES_LIST[@]}"; do
    if ynh_hide_warnings yunohost service status "${app}-${service_name}" >/dev/null; then
        yunohost service remove "${app}-${service_name}"
    fi
done

# Remove the dedicated systemd config
for service_name in "${SERVICES_LIST[@]}"; do
    ynh_config_remove_systemd "${app}-${service_name}"
done

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove a database if it exists, along with the associated user
for db_name in "${MONGO_DB_LIST[@]}"; do
    ynh_mongo_remove_db --db_user=$db_user --db_name="dontCode$tenant$db_name"
done

_remove_restart_script_and_sudoers

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
