#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
for service_name in "${SERVICES_LIST[@]}"; do
    if ynh_exec_warn_less yunohost service status "${app}-${service_name}" >/dev/null; then
        yunohost service remove "${app}-${service_name}"
    fi
done

# Remove the dedicated systemd config
for service_name in "${SERVICES_LIST[@]}"; do
    ynh_remove_systemd_config --service="${app}-${service_name}"
done

# Remove the dedicated NGINX config
ynh_remove_nginx_config

# Remove a database if it exists, along with the associated user
for db_name in "${MONGO_DB_LIST[@]}"; do
    ynh_mongo_remove_db --db_user=$db_user --db_name="dontCode$tenant$db_name"
done

# Remove mongo itself if not used anymore
ynh_remove_mongo

_remove_restart_script_and_sudoers

# Remove the log files
ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
