#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:$app "$install_dir"
#=================================================
# RESTORE THE DOCUMENTS DIRECTORY
#=================================================
ynh_script_progression "Restoring the document storage..."

ynh_restore "$data_dir"

mkdir -p $document_dir

chmod -R o-rwx,g+r "$data_dir"
chown -R $app:www-data "$data_dir"

#=================================================
# ADD SSH ACCESS
#=================================================

# Make sure the .ssh and files have the correct access rights
if [ -n "$public_key" ]; then
    ynh_script_progression "Restoring ssh access for dev..."

    chown -R "$app:$app" "$install_dir/.ssh"
    chmod 700 "$install_dir/.ssh"
    chmod 600 "$install_dir/.ssh/authorized_keys"

    _install_restart_script_and_sudoers
fi

#=================================================
# INSTALL MONGO
#=================================================
ynh_script_progression "Reinstalling MongoDB..."

# Install the required version of Mongo
ynh_install_mongo

#=================================================
# RESTORE THE MONGO DATABASES
#=================================================
ynh_script_progression "Restoring the Mongo databases..."

for db_name in "${MONGO_DB_LIST[@]}"; do
    ynh_mongo_setup_db --db_user="$db_user" --db_pwd="$db_pwd" --db_name="dontCode$tenant${db_name}"
    ynh_mongo_restore_db --database="dontCode$tenant$db_name" < "./dump-dontCode${tenant}${db_name}.bson"
done

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/logrotate.d/$app"
mkdir --parents /var/log/$app

for service_name in "${SERVICES_LIST[@]}"; do
    ynh_restore "/etc/systemd/system/${app}-${service_name}.service"
    systemctl enable "${app}-${service_name}.service" --quiet
    yunohost service add "${app}-${service_name}" --description="Dont-code platform ${service_name} service" --log="/var/log/${app}/${service_name}-${app}.log"
done

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's services..."

for service_name in "${SERVICES_LIST[@]}"; do
    ynh_systemctl --service="${app}-${service_name}" --action="start"

done

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
